version: '3'

services:
  backend:
    build:
      context: ./backend
      args:
        DJANGO_ALLOWED_HOSTS: $DJANGO_ALLOWED_HOSTS
        DJANGO_SECRET_KEY: $DJANGO_SECRET_KEY
        DJANGO_CORS_ALLOWED_ORIGINS: $DJANGO_CORS_ALLOWED_ORIGINS
    command: gunicorn backend.wsgi --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
  client:
    build:
      context: ./client
      args:
        API_URL: $REACT_APP_HOST_IP_ADDRESS
    volumes:
      - build_folder:/client/build
  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./webserver/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - build_folder:/var/www/client
    depends_on:
      - backend
      - client
volumes:
  build_folder:
