# Generated by Django 3.1.2 on 2020-10-16 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jp_en_endpoints', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationTextPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.CharField(max_length=10000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='mlalgorithm',
            name='parent_endpoint',
        ),
        migrations.RemoveField(
            model_name='mlalgorithmstatus',
            name='parent_mlalgorithm',
        ),
        migrations.RemoveField(
            model_name='mlrequest',
            name='parent_mlalgorithm',
        ),
        migrations.DeleteModel(
            name='Endpoint',
        ),
        migrations.DeleteModel(
            name='MLAlgorithm',
        ),
        migrations.DeleteModel(
            name='MLAlgorithmStatus',
        ),
        migrations.DeleteModel(
            name='MLRequest',
        ),
    ]
