# Generated by Django 3.1.2 on 2020-10-07 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('first_sentence', models.CharField(max_length=200)),
                ('publish_date', models.DateField()),
                ('post_link', models.CharField(max_length=200)),
            ],
        ),
    ]
