# Generated by Django 3.1.2 on 2021-01-14 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urdu_letter_endpoints', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LetterPredictionGet',
            new_name='PredictionLetterPost',
        ),
    ]
